parameters:
  slack.token: '%env(SLACK_TOKEN)%'
  slack.signing-secret: '%env(SLACK_SIGNING_SECRET)%'
  slack.auth-enabled: '%env(SLACK_AUTH_ENABLED)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude: '../src/{DependencyInjection,Entity,Kernel.php}'

  App\Security\Authenticator\SignedSlackAuthenticator:
    arguments:
      $signingSecret: '%slack.signing-secret%'
      $signEnabled: '%slack.auth-enabled%'